### ISSUE TITLE
Quotes are placed on the next line

### ISSUE THREAD

**Issue by xyproto** [mamaar/risotto#3]
Hi again!

When converting the following contents from JSX to JS:

~~~js
var CommentBox = React.createClass({
  render: function() {
    return (
      <div className="commentBox">
        Hello, world! I am a CommentBox.
      </div>
    );
  }
});
React.render(
  <CommentBox />,
  document.getElementById('content')
);
~~~

The output is this:

~~~js

var CommentBox = React.createClass({
    render: (function () {

        return React.createElement("div", {
            className: "commentBox"

        }, "Hello, world! I am a CommentBox.
      ");
    })

});
React.render(React.createElement(CommentBox, null), document.getElementById('content'));
~~~

The quote after "I am a CommentBox." ends up on the next line, which stops the JavaScript from working. (There is also an extra newline at the top, but that is just nitpicking).

The code sample is from the [React tutorial](https://facebook.github.io/react/docs/tutorial.html).

Cheers!

**Comment by mamaar** [comment]
Thanks. The last commits should fix this.

**Comment by xyproto** [comment]
It works! Thanks.
