### ISSUE TITLE
Parser, AST interfaces

### ISSUE THREAD

**Issue by TEugen** [mamaar/risotto#5]
You wrote `The parser and AST interfaces are still works-in-progress`, are you following the [ESTree spec](https://github.com/estree/estree/blob/master/spec.md)?

**Comment by mamaar** [comment]
The parser is not written by me, it's taken from [otto](https://github.com/robertkrimen/otto). I'll look into this later. Thanks for the link!

**Comment by mamaar** [comment]
Hi, @TEugen 
It doesn't seem like it follows the ESTree spec completely, but I'm not sure I'll bother putting time into that if Risotto proves to work with the current parser. Would it be worth it, you think?

**Comment by TEugen** [comment]
I'm thinking to fork otto's parser and implement a ESTree spec compliant version in Go. I'm kinda new to Go / parsers and learning how to best approach it.

In my opinion it's worth it, as I want to make it easy to create processing (build) tools for JS. Main reason over Node.js is that I want the tools to be available as a binary.

**Comment by mamaar** [comment]
I looked a little more into it and agree. Time to start go-estree
